name: tkSeichi
version: 0.2.1
main: tk.seichi.Control
commands:
  tp-above:
    description:  player wo siteiblock ue ni tobasu.
    usage: /<command> [distance] (デフォルトは20ブロック)
    default:  true